apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-15T03:58:06Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "5754"
  uid: d73167f5-00cc-45c7-807e-0c1b66918fce
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.96.222.252
  clusterIPs:
  - 10.96.222.252
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31605
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
